### ISSUE TITLE
aws managed key alias/aws/sns does not have required permissions to enable compatibility between the event source (AWS CodeStar Notifications) and the encrypted topic.

### ISSUE THREAD

**Issue by dppuligu** [aws-samples/aws-blog-codepipeline-third-party-git-build-status#2]
Using the template as it is creates SNS topic with encryption enabled using the key `alias/aws/sns`. The key does not have the below statement as mentioned in [Configure Amazon SNS topics for notifications](https://docs.aws.amazon.com/dtconsole/latest/userguide/set-up-sns.html) at step 6.

        {
            "Effect": "Allow",
            "Principal": {
                "Service": "codestar-notifications.amazonaws.com"
            },
            "Action": [
                "kms:GenerateDataKey*",
                "kms:Decrypt"
            ],
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "kms:ViaService": "sns.us-east-2.amazonaws.com"
                }
            }
        }

Instead, the template should use conditions giving user the choice to enable encryption or not and when check it creates a custom key with correct permissions.

**Comment by dppuligu** [comment]
[PR](https://github.com/aws-samples/aws-blog-codepipeline-third-party-git-build-status/pull/3)

**Comment by p4cket** [comment]
@dppuligu  thanks for request and PR, i asked for one change and after this we can merge changes

**Comment by p4cket** [comment]
PR was merged!
